version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    env_file:
      - .env
    networks:
      - zoppy-network

networks:
  zoppy-network:
    driver: bridge